import {
  fecthCategoriesProgress,
  fecthExpensesPerCategory,
  fecthPlanProgress,
  fetchCategoriesByPlan,
  fetchCategoryById,
  fetchMonthlyBalance,
  fetchPlanById,
  fetchUserCategories,
  fetchUserPlans,
} from './apiConsumer'
import {
  addCategory,
  addCategoryBatch,
  addPlan,
  addTransaction,
  deleteCategory,
  deletePlan,
  updateCategory,
  updatePlan,
} from './apiMutations'

export const Api = {
  monthlyBalance: fetchMonthlyBalance,
  plans: fetchUserPlans,
  planById: fetchPlanById,
  planProgress: fecthPlanProgress,
  categoriesProgress: fecthCategoriesProgress,
  expensesPerCategory: fecthExpensesPerCategory,
  categories: fetchUserCategories,
  categoryById: fetchCategoryById,
  categoriesByPlan: fetchCategoriesByPlan,
  addPlan,
  addCategory,
  addCategoryBatch,
  addTransaction,
  deletePlan,
  deleteCategory,
  updatePlan,
  updateCategory,
}
